namespace Pure.Blazor.Components.Icons;

public enum PureIcons
{
    IconCheck,
    IconSpin,
    IconOpenCircle,
    IconChevronDoubleLeft,
    IconChevronLeft,
    IconChevronDoubleRight,
    IconChevronRight,
    IconChevronUpDown,
    IconChevronDown,
    IconIdentity,
    IconSettings,
    IconSubscription,
    IconDashboard,
    IconArticle,
    IconNewspaper,
    IconPhoto,
    IconBlocks,
    IconBuilder,
    IconFunction,
    IconRectangleStack,
    IconBeaker,
    IconSignOut,
    IconEllipsis,
    IconLanguage,
    IconSquareStack,
    IconCloud,
    IconCopy,
    IconHeart,
    IconInfo,
    IconArchive,
    IconNewFolder,
    IconNewFile,
    IconGrabHandle
}
